apiVersion: v1
kind: ConfigMap
metadata:
  name: mydoc-frontend-nginx
  namespace: mydoc
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;

      root /usr/share/nginx/html;
      index index.html;

      add_header X-Content-Type-Options "nosniff" always;
      add_header X-Frame-Options "SAMEORIGIN" always;
      add_header X-XSS-Protection "1; mode=block" always;
      add_header Referrer-Policy "no-referrer-when-downgrade" always;
      add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
      server_tokens off;

      location / { try_files $uri $uri/ /index.html; }

      # proxy angular /api to backend service
      location /api/ {
        proxy_pass http://doctor-appointment-backend.mydoc.svc.cluster.local:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
