apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mydoc
  labels: { app: mysql }
spec:
  clusterIP: None
  selector: { app: mysql }
  ports:
    - name: mysql
      port: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mydoc
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
            - secretRef: { name: mysql-secret }
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "1Gi" }
  volumeClaimTemplates:
    - metadata: { name: mysql-data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
